name: Set Environment Secret

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Secret as Environment Variable
      run: |
        echo "HUGGING_FACE_TOKEN=$HUGGING_FACE_TOKEN"
      env:
        HUGGING_FACE_ACCESS_TOKEN: ${{ secrets.HUGGING_FACE_ACCESS_TOKEN }}
